# Generated by Django 3.1.5 on 2021-01-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentInformationSystem', '0005_auto_20210123_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=5000)),
                ('result_text', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='guardianContactNumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardianEmail',
            field=models.EmailField(default='@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='motherTongue',
            field=models.CharField(choices=[('English', 'English'), ('Chinese', 'Chinese'), ('Other', 'Other')], default='Chinese', max_length=7),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Buddhism', 'Buddhism'), ('Catholic', 'Catholic'), ('Islam', 'Islam'), ('Jehovahs Witnesses', 'Jehovahs Witnesses'), ('Taoism', 'Taoism'), ('Yiguandao', 'Yiguandao'), ('Protestantism', 'Protestantism'), ('Other', 'Other')], default='Catholic', max_length=32),
        ),
    ]
