# Generated by Django 3.1.5 on 2021-01-28 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentInformationSystem', '0006_auto_20210128_0232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultTexts',
            new_name='ResultText',
        ),
    ]
